# Generated by Django 4.2.16 on 2025-05-17 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_remove_product_image_url_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="affiliate_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Commission rate for affiliate sales (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="ad_type",
            field=models.CharField(
                choices=[
                    ("banner", "Banner"),
                    ("text", "Text"),
                    ("video", "Video"),
                    ("native", "Native"),
                    ("adsense", "Google AdSense"),
                ],
                default="banner",
                help_text="Type of ad",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Ad copy or ad network script (e.g., AdSense code)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for ad notifications, defaults to staff user's email",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for low stock notifications, defaults to staff user's email",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_url",
            field=models.URLField(
                help_text="Affiliate or purchase URL",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
