# Generated by Django 4.2.16 on 2025-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketing",
            "0003_product_affiliate_commission_rate_alter_ad_ad_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_affiliate",
            field=models.BooleanField(
                default=True,
                help_text="True for affiliate ads, False for ad network banners",
            ),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="commission_earned",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Commission from affiliate conversions",
                max_digits=10,
            ),
        ),
    ]
